-- Generated by scripts/build_poison_catalog.py; see CLIENT_COMPATIBILITY.md.
local addon = _G.NoPoizen
if not addon then
	return
end
addon.weaponPoisonCatalogs = {
	forever = {
		[7] = { spellID = 2823, usesCharges = true }, -- Deadly Poison
		[8] = { spellID = 2824, usesCharges = true }, -- Deadly Poison II
		[22] = { spellID = 3408, usesCharges = false }, -- Crippling Poison
		[23] = { spellID = 8693, usesCharges = true }, -- Mind-numbing Poison II
		[35] = { spellID = 5761, usesCharges = true }, -- Mind Numbing Poison
		[323] = { spellID = 8679, usesCharges = true }, -- Instant Poison
		[324] = { spellID = 8686, usesCharges = true }, -- Instant Poison II
		[325] = { spellID = 8688, usesCharges = true }, -- Instant Poison III
		[603] = { spellID = 11202, usesCharges = false }, -- Crippling Poison II
		[623] = { spellID = 11338, usesCharges = true }, -- Instant Poison IV
		[624] = { spellID = 11339, usesCharges = true }, -- Instant Poison V
		[625] = { spellID = 11340, usesCharges = true }, -- Instant Poison VI
		[626] = { spellID = 11355, usesCharges = true }, -- Deadly Poison III
		[627] = { spellID = 11356, usesCharges = true }, -- Deadly Poison IV
		[643] = { spellID = 11399, usesCharges = true }, -- Mind-Numbing Poison III
		[703] = { spellID = 13219, usesCharges = true }, -- Wound Poison
		[704] = { spellID = 13225, usesCharges = true }, -- Wound Poison II
		[705] = { spellID = 13226, usesCharges = true }, -- Wound Poison III
		[706] = { spellID = 13227, usesCharges = true }, -- Wound Poison IV
		[2630] = { spellID = 25351, usesCharges = true }, -- Deadly Poison V
	},
	era = {
		[7] = { spellID = 2823, usesCharges = true }, -- Deadly Poison
		[8] = { spellID = 2824, usesCharges = true }, -- Deadly Poison II
		[22] = { spellID = 3408, usesCharges = false }, -- Crippling Poison
		[23] = { spellID = 8693, usesCharges = true }, -- Mind-numbing Poison II
		[35] = { spellID = 5761, usesCharges = true }, -- Mind Numbing Poison
		[323] = { spellID = 8679, usesCharges = true }, -- Instant Poison
		[324] = { spellID = 8686, usesCharges = true }, -- Instant Poison II
		[325] = { spellID = 8688, usesCharges = true }, -- Instant Poison III
		[603] = { spellID = 11202, usesCharges = false }, -- Crippling Poison II
		[623] = { spellID = 11338, usesCharges = true }, -- Instant Poison IV
		[624] = { spellID = 11339, usesCharges = true }, -- Instant Poison V
		[625] = { spellID = 11340, usesCharges = true }, -- Instant Poison VI
		[626] = { spellID = 11355, usesCharges = true }, -- Deadly Poison III
		[627] = { spellID = 11356, usesCharges = true }, -- Deadly Poison IV
		[643] = { spellID = 11399, usesCharges = true }, -- Mind-Numbing Poison III
		[703] = { spellID = 13219, usesCharges = true }, -- Wound Poison
		[704] = { spellID = 13225, usesCharges = true }, -- Wound Poison II
		[705] = { spellID = 13226, usesCharges = true }, -- Wound Poison III
		[706] = { spellID = 13227, usesCharges = true }, -- Wound Poison IV
		[2630] = { spellID = 25351, usesCharges = true }, -- Deadly Poison V
		[7254] = { spellID = 439462, usesCharges = false }, -- Sebacious Poison
		[7255] = { spellID = 439464, usesCharges = false }, -- Numbing Poison
		[7256] = { spellID = 439465, usesCharges = false }, -- Atrophic Poison
		[7542] = { spellID = 458821, usesCharges = false }, -- Occult Poison I
		[7651] = { spellID = 1214171, usesCharges = false }, -- Occult Poison II
	},
	tbc = {
		[7] = { spellID = 2823, usesCharges = false }, -- Deadly Poison
		[8] = { spellID = 2824, usesCharges = false }, -- Deadly Poison II
		[22] = { spellID = 3408, usesCharges = false }, -- Crippling Poison
		[23] = { spellID = 8693, usesCharges = false }, -- Mind-numbing Poison II
		[35] = { spellID = 5761, usesCharges = false }, -- Mind Numbing Poison
		[323] = { spellID = 8679, usesCharges = false }, -- Instant Poison
		[324] = { spellID = 8686, usesCharges = false }, -- Instant Poison II
		[325] = { spellID = 8688, usesCharges = false }, -- Instant Poison III
		[603] = { spellID = 11202, usesCharges = false }, -- Crippling Poison II
		[623] = { spellID = 11338, usesCharges = false }, -- Instant Poison IV
		[624] = { spellID = 11339, usesCharges = false }, -- Instant Poison V
		[625] = { spellID = 11340, usesCharges = false }, -- Instant Poison VI
		[626] = { spellID = 11355, usesCharges = false }, -- Deadly Poison III
		[627] = { spellID = 11356, usesCharges = false }, -- Deadly Poison IV
		[643] = { spellID = 11399, usesCharges = false }, -- Mind-Numbing Poison III
		[703] = { spellID = 13219, usesCharges = false }, -- Wound Poison
		[704] = { spellID = 13225, usesCharges = false }, -- Wound Poison II
		[705] = { spellID = 13226, usesCharges = false }, -- Wound Poison III
		[706] = { spellID = 13227, usesCharges = false }, -- Wound Poison IV
		[2630] = { spellID = 25351, usesCharges = false }, -- Deadly Poison V
		[2640] = { spellID = 26785, usesCharges = false }, -- Anesthetic Poison
		[2641] = { spellID = 26891, usesCharges = false }, -- Instant Poison VII
		[2642] = { spellID = 26967, usesCharges = false }, -- Deadly Poison VI
		[2643] = { spellID = 27186, usesCharges = false }, -- Deadly Poison VII
		[2644] = { spellID = 27188, usesCharges = false }, -- Wound Poison V
	},
	titan = {
		[7] = { spellID = 2823, usesCharges = false }, -- Deadly Poison
		[8] = { spellID = 2824, usesCharges = false }, -- Deadly Poison II
		[22] = { spellID = 3408, usesCharges = false }, -- Crippling Poison
		[35] = { spellID = 5761, usesCharges = false }, -- Mind Numbing Poison
		[323] = { spellID = 8679, usesCharges = false }, -- Instant Poison
		[324] = { spellID = 8686, usesCharges = false }, -- Instant Poison II
		[325] = { spellID = 8688, usesCharges = false }, -- Instant Poison III
		[623] = { spellID = 11338, usesCharges = false }, -- Instant Poison IV
		[624] = { spellID = 11339, usesCharges = false }, -- Instant Poison V
		[625] = { spellID = 11340, usesCharges = false }, -- Instant Poison VI
		[626] = { spellID = 11355, usesCharges = false }, -- Deadly Poison III
		[627] = { spellID = 11356, usesCharges = false }, -- Deadly Poison IV
		[703] = { spellID = 13219, usesCharges = false }, -- Wound Poison
		[704] = { spellID = 13225, usesCharges = false }, -- Wound Poison II
		[705] = { spellID = 13226, usesCharges = false }, -- Wound Poison III
		[706] = { spellID = 13227, usesCharges = false }, -- Wound Poison IV
		[2630] = { spellID = 25351, usesCharges = false }, -- Deadly Poison V
		[2640] = { spellID = 26785, usesCharges = false }, -- Anesthetic Poison
		[2641] = { spellID = 26891, usesCharges = false }, -- Instant Poison VII
		[2642] = { spellID = 26967, usesCharges = false }, -- Deadly Poison VI
		[2643] = { spellID = 27186, usesCharges = false }, -- Deadly Poison VII
		[2644] = { spellID = 27188, usesCharges = false }, -- Wound Poison V
		[3768] = { spellID = 57967, usesCharges = false }, -- Instant Poison VIII
		[3769] = { spellID = 57968, usesCharges = false }, -- Instant Poison IX
		[3770] = { spellID = 57972, usesCharges = false }, -- Deadly Poison VIII
		[3771] = { spellID = 57973, usesCharges = false }, -- Deadly Poison IX
		[3772] = { spellID = 57977, usesCharges = false }, -- Wound Poison VI
		[3773] = { spellID = 57978, usesCharges = false }, -- Wound Poison VII
		[3774] = { spellID = 57982, usesCharges = false }, -- Anesthetic Poison II
	},
}
