"""Regenerate reviewed weapon poison IDs from exact Wago DB2 CSV exports.
Usage: python3 scripts/build_poison_catalog.py /path/to/csv-cache
See CLIENT_COMPATIBILITY.md for source builds and selection rules.
"""
import csv
import hashlib
import json
import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parents[1]
cache = pathlib.Path(sys.argv[1])
profiles = {"forever": "1.60.1.70009", "era": "1.15.9.69722", "tbc": "2.5.6.69795", "titan": "3.80.2.69874"}
family = re.compile(r"^(Deadly|Instant|Wound|Crippling|Mind[ -][Nn]umbing|Sebacious|Numbing|Atrophic|Occult|Anesthetic) Poison(?: [IVX]+)?$", re.I)
lua = ["-- Generated by scripts/build_poison_catalog.py; see CLIENT_COMPATIBILITY.md.", "local addon = _G.NoPoizen", "if not addon then return end", "addon.weaponPoisonCatalogs = {"]
evidence = {}
for profile, build in profiles.items():
    tables = {}
    hashes = {}
    for table in ["SpellName", "SpellEffect", "SpellItemEnchantment", "Spell"]:
        path = cache / (build + "-" + table + ".csv")
        data = path.read_bytes()
        hashes[table] = hashlib.sha256(data).hexdigest()
        tables[table] = list(csv.DictReader(data.decode("utf-8-sig").splitlines()))
    names = {r["ID"]: r["Name_lang"] for r in tables["SpellName"]}
    enchants = {r["ID"]: r for r in tables["SpellItemEnchantment"]}
    found = {}
    for effect in tables["SpellEffect"]:
        spell = effect["SpellID"]
        enchant = effect["EffectMiscValue_0"]
        if effect["Effect"] not in (["360"] if profile == "forever" else ["54"]):
            continue
        if not family.fullmatch(names.get(spell, "")) or enchant not in enchants:
            continue
        row = enchants[enchant]
        if not family.fullmatch(row["Name_lang"]):
            continue
        found[int(enchant)] = {"spellID": int(spell), "name": row["Name_lang"], "usesCharges": int(row["Charges"]) > 0}
    assert len(found) >= 20, (profile, len(found))
    lua.append("\t" + profile + " = {")
    for enchant, row in sorted(found.items()):
        lua.append("\t\t[%d] = { spellID = %d, usesCharges = %s }, -- %s" % (enchant, row["spellID"], str(row["usesCharges"]).lower(), row["name"]))
    lua.append("\t},")
    evidence[profile] = {"build": build, "sha256": hashes, "enchants": found}
    if profile == "era":
        evidence[profile]["automaticPoison"] = {"name": "Deadly Brew", "engravingSpellID": 400080,
                                              "itemEnchantmentID": 6708, "abilitySpellIDs": [399969, 399965, 433521]}
lua.append("}")
(root / "PoisonData.lua").write_text("\n".join(lua) + "\n")
(root / "scripts/poison-data-sources.json").write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n")
